export const LOGISTICS_SERVICES = ["FACTORY_PICKUP", "DOMESTIC_TRANSPORT", "WAREHOUSING", "FREIGHT_FORWARDING", "SEA_FREIGHT", "AIR_FREIGHT", "RAIL_FREIGHT", "CUSTOMS_BROKERAGE", "LAST_MILE", "CARGO_INSURANCE"] as const;
export const SHIPMENT_MODES = ["SEA_FCL", "SEA_LCL", "AIR", "RAIL", "ROAD", "COURIER", "MULTIMODAL"] as const;
export const SHIPMENT_STATUSES = ["PENDING", "BOOKED", "PICKED_UP", "AT_WAREHOUSE", "AT_ORIGIN_PORT", "DEPARTED", "IN_TRANSIT", "AT_DESTINATION_PORT", "CUSTOMS_CLEARANCE", "OUT_FOR_DELIVERY", "DELIVERED", "EXCEPTION", "CANCELLED"] as const;
export const SHIPMENT_MILESTONES = ["FACTORY", "PICKUP", "WAREHOUSE", "ORIGIN_PORT", "DEPARTED", "IN_TRANSIT", "DESTINATION_PORT", "CUSTOMS", "LAST_MILE", "DELIVERED", "EXCEPTION"] as const;
