/**
 * Regenerates src/lib/product-photo-assignments.ts: one stock photo per catalogue product, unique
 * within each product type as long as the pool is big enough. Run after adding photos or seeding:
 *   DATABASE_URL=… npx tsx scripts/assign-product-photos.ts
 * Live products are assigned first so drafts are the ones that wrap round when a pool runs short.
 */
import { writeFileSync } from "node:fs";
import { Pool } from "pg";
import { PRODUCT_PHOTO_POOLS, productPhotoKey } from "../src/lib/product-photos";

async function main() {
  const pg = new Pool({ connectionString: process.env.DATABASE_URL });
  const { rows } = await pg.query<{ slug: string; title: string; status: string }>(
    `SELECT slug, title, status FROM products WHERE deleted_at IS NULL ORDER BY (status = 'ACTIVE') DESC, slug`,
  );
  await pg.end();
  const next: Record<string, number> = {};
  const out: Array<[string, string]> = [];
  const short: Record<string, number> = {};
  for (const r of rows) {
    const key = productPhotoKey(r.title);
    if (!key) continue;
    const pool = PRODUCT_PHOTO_POOLS[key];
    const i = next[key] ?? 0;
    next[key] = i + 1;
    if (i >= pool.length) short[key] = (short[key] ?? 0) + 1;
    out.push([r.slug, pool[i % pool.length]]);
  }
  const body = out.map(([slug, id]) => `  ${JSON.stringify(slug)}: ${JSON.stringify(id)},`).join("\n");
  writeFileSync(
    "src/lib/product-photo-assignments.ts",
    `// Generated by scripts/assign-product-photos.ts — one stock photo per seeded product. Do not edit by hand.\nexport const PHOTO_ASSIGNMENTS: Record<string, string> = {\n${body}\n};\n`,
  );
  console.log(`assigned ${out.length} products; pools that wrapped:`, short);
}

main();
